services:
  web:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: pastebin
      DB_NAME: pastebin
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8000:5000"
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: pastebin
      MYSQL_USER: pastebin
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  db-migrations:
    image: flyway/flyway
    entrypoint: ["/bin/sh", "-c"]
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command: >
      "flyway
      -url=jdbc:mysql://db?allowPublicKeyRetrieval=true
      -schemas=pastebin
      -user=root
      -password=$DB_ROOT_PASSWORD
      -connectRetries=60
      migrate"
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

volumes:
  db-data:
