name: Anchore Syft SBOM scan

on:
  push:
    branches: "**"

# Adjusted permissions to follow least privilege access
permissions:
  contents: write # Required to upload to the Dependency submission API
  statuses: write  # Allows writing commit statuses

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Scan the image and upload dependency results
        id: sbom_scan
        uses: anchore/sbom-action@latest
        with:
          image: "localbuild/testimage:latest"
          artifact-name: image.spdx.json
          dependency-snapshot: true

      - name: List SBOM Output Directory
        run: |
          echo "Contents of the SBOM action output directory:"
          ls -al /tmp/sbom-action-* || true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: /tmp/sbom-action-*/image.spdx.json

      - name: Check Private Key ID
        run: |
          echo "${{ secrets.INTOTOPRIVATE }}" > mykey.priv
          chmod 600 mykey.priv
          KEY_ID=$(in-toto key id --key mykey.priv)
          echo "Private Key ID: ${KEY_ID}"

      - name: Check Public Key Info
        run: |
          echo "${{ secrets.INTOTOPUB }}" > mykey.pub
          KEY_ID_PUBLIC=$(in-toto key id --key mykey.pub)
          echo "Public Key ID: ${KEY_ID_PUBLIC}"
   

      - name: Install in-toto
        run: |
          pip install in-toto

      - name: Create Private Key File
        env:
          IN_TOTO_PRIVATE_KEY: ${{ secrets.INTOTOPRIVATE }}
        run: |
          echo "${IN_TOTO_PRIVATE_KEY}" > mykey.priv
          chmod 600 mykey.priv

      - name: Sign SBOM with in-toto
        run: |
          in-toto-sign -f layout.json --key mykey.priv --material /tmp/sbom-action-*/image.spdx.json --product /tmp/sbom-action-*/image.spdx.json
