name: Anchore Syft SBOM scan

on:
  push:
    branches: "**"

# Adjusted permissions to follow least privilege access
permissions:
  contents: write # Required to upload to the Dependency submission API
  statuses: write  # Allows writing commit statuses

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Scan the image and upload dependency results
        id: sbom_scan
        uses: anchore/sbom-action@latest
        with:
          image: "localbuild/testimage:latest"
          artifact-name: image.spdx.json
          dependency-snapshot: true

      - name: List SBOM Output Directory
        run: |
          echo "Contents of the SBOM action output directory:"
          ls -al /tmp/sbom-action-* || true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: /tmp/sbom-action-*/image.spdx.json

      - name: Install in-toto
        run: |
          pip install in-toto

      - name: Create Private Key File
        run: |
          echo "${{ secrets.INTOTOPRIVATE }}" > mykey.priv
          chmod 600 mykey.priv

      - name: Sign Artifact
        env:
          ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT: image.spdx.json
        run: |
          set -e
          # List the contents to confirm file paths
          ls -al /tmp/sbom-action-*/image.spdx.json
          in-toto-sign -f layout.json --key mykey.priv -m /tmp/sbom-action-*/image.spdx.json -p /tmp/sbom-action-*/image.spdx.json
