name: Anchore Syft SBOM scan

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # Required to upload to the Dependency submission API

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest

    - name: Scan the image and upload dependency results
      id: sbom_scan
      uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
      with:
        image: "localbuild/testimage:latest"
        artifact-name: image.spdx.json
        dependency-snapshot: true

    - name: List SBOM Output Directory
      run: |
        echo "Contents of the SBOM action output directory:"
        ls -al /tmp/sbom-action-* || true

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: /tmp/sbom-action-*/image.spdx.json # Use wildcard to match the dynamic directory
