name: Anchore Syft SBOM scan

on:
  push:
    branches: "**"

# Adjusted permissions to follow least privilege access
permissions:
  contents: write # Required to upload to the Dependency submission API
  statuses: write   # Allows writing commit statuses

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Scan the image and upload dependency results
        id: sbom_scan
        uses: anchore/sbom-action@latest
        with:
          image: "localbuild/testimage:latest"
          artifact-name: image.spdx.json
          dependency-snapshot: true

      - name: List SBOM Output Directory
        run: |
          echo "Contents of the SBOM action output directory:"
          ls -al /tmp/sbom-action-* || true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: /tmp/sbom-action-*/image.spdx.json

      - name: Install in-toto
        run: |
          pip install in-toto


      - name: Sign SBOM
        run: |
          in-toto-sign --layout layout.json --step-name sbom-generation --key ${{ secrets.INTOTOPRIVATE }} --material /tmp/sbom-action-*/image.spdx.json --product /tmp/sbom-action-*/image.spdx.json

      - name: Define in-toto layout
        run: |
          echo '{
            "steps": [
              {
                "name": "sbom-generation",
                "expected_materials": ["image.spdx.json"],
                "expected_products": ["image.spdx.json"],
                "public_key": "${{ secrets.INTOTOPUB }}"
              }
            ]
          }' > layout.json
