name: In-toto Attestation

on:
  push:
    branches: "**"  # Trigger on all branches

permissions:
  contents: write  # Required for uploading artifacts
  statuses: write   # Allows writing commit statuses
  
jobs:
  Attest-Artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install In-toto
      run: |
        python -m pip install --upgrade pip
        pip install in-toto

    - name: Generate In-toto Attestation
      env:
        INTOTOPUB: ${{ secrets.INTOTOPUB }}       # Public key
        INTOTOPRIVATE: ${{ secrets.INTOTOPRIVATE }} # Private key
      run: |
        # Generate the attestation
        in-toto record --layout attestation.layout \
          --link-name build \
          --material-path Dockerfile \
          --material-path . \
          --predicate "{\"predicateType\": \"https://in-toto.io/Predicate/Attestation\", \"subject\": [{\"name\": \"localbuild/testimage:latest\"}], \"claim\": {\"summary\": \"Image built and scanned successfully.\"}}" \
          --private-key "$INTOTOPRIVATE" \
          --public-key "$INTOTOPUB" \
          attestation.json

    - name: Upload Attestation Artifact
      uses: actions/upload-artifact@v4
      with:
        name: attestation
        path: attestation.json

