name: Black Formatter

on:
  push:
    branches:
      - main  # Default branch
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated from v2 to v3, compatible with Node.js 16

      - name: Set up Python
        uses: actions/setup-python@v4 # Updated from v2 to v4, compatible with Node.js 16
        with:
          python-version: '3.12'  # Changed from v3.8 to 3.12

      - name: Install dependencies
        run: |
          pip install black

      - name: Run Black
        run: |
          black --check .
