name: In-Toto Workflow

on:
  push:
    branches: "**"  # For all pushes

permissions:
  contents: read # default to read-only
  statuses: write   # Allows writing commit statuses

jobs:
  in-toto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install In-Toto
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install in-toto

      - name: Generate Metadata for Build
        id: build
        #run: |
        #  # Archive the entire src folder
        #  tar -czf output-artifact.tar.gz src  # Included the entire ./src folder
        #  # Create in-toto metadata using the private key from GitHub Secrets
        #  in-toto-record -n build --products output-artifact.tar.gz --key <(echo "${{ secrets.INTOTOPRIVATE }}")

        run: |
          set -e
          echo "Archiving source code..."
          tar -czf output-artifact.tar.gz src
          echo "Starting in-toto record for build..."
          in-toto-record start -n build --key <(echo "${{ secrets.INTOTOPRIVATE }}")
          echo "Generating in-toto metadata for build..."
          in-toto-record stop --products output-artifact.tar.gz

      - name: Generate Metadata for Test
        id: test
        run: |
          # Run tests here
          # Create in-toto metadata using the private key from GitHub Secrets
          in-toto-record -n test --products test-results.xml --key <(echo "${{ secrets.INTOTOPRIVATE }}")

      - name: Generate Metadata for Deploy
        id: deploy
        run: |
          # Deploy your artifact here
          # Create in-toto metadata using the private key from GitHub Secrets
          in-toto-record -n deploy --products deployed-artifact --key <(echo "${{ secrets.INTOTOPRIVATE }}")

      - name: Verify Artifacts
        run: |
          # Verify the artifacts using the public key from GitHub Secrets
          in-toto-verify --layout layout.json --key <(echo "${{ secrets.INTOTOPUB }}")

