# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read
  pull-requests: write  # Permission to update pull request status
  statuses: write   # Allows writing commit statuses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # python-version: "3.12"    # omitting version uses .python-version file
        cache: "pip"                # cache dependencies for faster build

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

<<<<<<< HEAD
    - name: Format with Black
      id: black
      run: |
        black --check .

    - name: Test with pytest and coverage
      id: tests
      run: |
        pytest --cov=src tests/
        coverage report --fail-under=90

    - name: Integration tests
      run: |
        pytest integration/

=======
>>>>>>> 56fb4fe (Remove unnecessary checks ;))
    - name: Set commit status for Commit Request review
      run: |
        if [[ "${{ steps.black.outcome }}" == "success" && "${{ steps.tests.outcome }}" == "success" ]]; then
          status="success"
        else
          status="failure"
        fi
        
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        -d "{\"state\": \"$status\", \"context\": \"Python application\"}"
