name: Secret Scan2

on:
  push:
    branches: '**'  # all branches
      
  pull_request:
    branches:
      - main

permissions:
  contents: read    # Allows reading repository contents
  statuses: write   # Allows writing commit statuses
  actions: write

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TruffleHog
        run: pip install truffleHog

      - name: Run TruffleHog
        id: trufflehog
        run: |
          #trufflehog --regex . || true          # Scan all folders and files
          output=$(trufflehog --regex --json . 2>&1) || true
          echo "$output" > secrets.json                  # Save full output for debugging
          cat secrets.json                               # Print the JSON structure for inspection
         
          #echo "$output" | jq -r '.stringsFound[]' > found_secrets.txt || true  # Extract found secrets
         
          echo "$output" | jq -r '.branch' > found_secrets.txt || true  # Extract branch names
          cat found_secrets.txt
          
      - name: Check for secrets
        id: check-secrets
        run: |
          #if [ $? -ne 0 ]; then
          if [ -s found_secrets.txt ]; then
            echo "Secrets found in the repository!"
            echo "status=fail" >> $GITHUB_ENV
            cat found_secrets.txt
            exit 1
          else
            echo "No secrets found."
            echo "status=success" >> $GITHUB_ENV
          fi

      - name: Upload Secrets as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-secrets
          path: |
            secrets.json
            found_secrets.txt
            

      - name: Set commit status
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -d "{\"state\": \"${{ env.status }}\", \"context\": \"Secret Scan\"}"
