name: trivy-sbom

on:
  push:
    branches:
      - '**'  # This will match all branches
  pull_request:
    branches:
      - main
  schedule:
    - cron: '29 13 * * 3'

permissions:
  contents: read    # Allows reading repository contents
  statuses: write   # Allows writing commit statuses

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SBOM file
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-20.04"

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build the Docker image from Dockerfile
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/csgy-9223-group4/lab1:${{ github.sha }} .

      # Step 3: Install Trivy (ensures Trivy is available for subsequent steps)
      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb

      # Step 4: Cache Trivy DB to avoid repeated downloads
      - name: Cache Trivy DB
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-v0.38.3-${{ github.sha }}
          restore-keys: |
            trivy-db-${{ runner.os }}-v0.38.3-

      # Step 5: Generate SBOM with Trivy and log output
      - name: Generate SBOM with Trivy
        run: |
          trivy sbom --config .trivy.yml docker.io/csgy-9223-group4/lab1:${{ github.sha }} > sbom.json
          cat sbom.json  # Output the contents of the SBOM file to logs for debugging

      # Step 6: Check if the SBOM file exists and has content
      - name: Check if SBOM file exists and has content
        run: |
          if [ -f sbom.json ]; then
            echo "SBOM file exists with size: $(stat -c %s sbom.json)"
          else
            echo "SBOM file not found!"
            exit 1
          fi

      # Step 7: Upload SBOM as artifact
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
