name: SBOM Creation and Dependency Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  create-sbom-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Build the Docker image (assuming you're scanning a Docker image)
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      # Step to generate SBOM using Anchore Syft
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@latest
        id: sbom
        with:
          image: localbuild/testimage:latest
          artifact-name: sbom.json  # This is the output SBOM file

      # Upload the generated SBOM for further usage
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      # Download the SBOM artifact for Trivy to use
      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: sbom
          path: ./artifacts

      # Run Trivy dependency scan using the SBOM
      - name: Run Trivy dependency scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          input: "./artifacts/sbom.json"  # Path to the SBOM file
          scan-type: "license"  # Scan for vulnerabilities in dependencies
          format: "json"  # Output format
          output: "trivy-dependency-report.json"  # Output file for the report
          severity: "HIGH,CRITICAL"  # Filter for high and critical severity issues

      # Upload the Trivy dependency report
      - name: Upload Trivy dependency report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-dependency-report
          path: trivy-dependency-report.json
