name: Triv License Image

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: write

jobs:
  sbom-and-license-check:
    runs-on: ubuntu-latest

    steps:
# Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4


# Step 2: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest


    
  # Step 3
      - name: Install Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz | tar xz -C /usr/local/bin

    
  # Step 4
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

         #Create Snapshot
          create-snapshot: true  # This ensures that a snapshot is created and uploaded
          snapshot-branch: main  # Ensure the snapshot is linked to the default branch (e.g., main)

      - name: Upload Snapshot
        uses: actions/upload-artifact@v4
        with:
          name: dependency-snapshot
          path: ".github/workflows/outputs/dependency-snapshot.json"  # Path to the snapshot file
       
