name: Trivy License Image GitHub

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: write

jobs:
  sbom-and-license-check:
    runs-on: ubuntu-latest

    steps:
# Step 1: Checkout the code
      - name: Step 1 Checkout the code
        uses: actions/checkout@v4


# Step 2: Build the Docker image
      - name: Step 2 Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest


    
  # Step 3
      - name: Step 3 Install Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz | tar xz -C /usr/local/bin
    
  # Step 4
      - name: Step 4 Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          severity: "MEDIUM,HIGH,CRITICAL"
          github-pat: ${{ secrets.GITHUB_TOKEN }}

          
# Step 5
      - name: Step 5 Upload Snapshot
        uses: actions/upload-artifact@v4
        with:
          name: dependency-snapshot
          path: '${{ github.workspace }}/dependency-results.sbom.json'
          
# Step 6 Step 6 Run Trivy License Scan
      - name: Step 6 Run Trivy License Scan
        run: |
          trivy image --format json --output trivy-license.sarif --scanners license --severity UNKNOWN,HIGH,CRITICAL localbuild/testimage:latest

        env:
          #TRIVY_FORMAT: sarif
          TRIVY_FORMAT: github
          TRIVY_OUTPUT: trivy-license.sarif

  # Fix Trivy SARIF Structure
      - name: Fix Trivy SARIF Structure
        run: |
          if [ -f trivy-license.sarif ]; then
            jq 'del(.SchemaVersion, .CreatedAt, .ArtifactName, .ArtifactType, .Metadata, .Results) |
              . + {version: "2.1.0", runs: [{tool: {driver: {name: "Trivy", version: "0.40.0"}}, results: []}]} ' trivy-license.sarif > trivy-license-fixed.sarif
            mv trivy-license-fixed.sarif trivy-license.sarif
          else
            echo "SARIF file not found"
            exit 1
          fi
        shell: bash
          
# Step 7: Step 7 Upload the SARIF report to GitHub
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-license.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
