name: SBOM Creation and Dependency Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  create-sbom-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Build the Docker image (assuming you're scanning a Docker image)
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      # Step to generate SBOM using Anchore Syft
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@latest
        id: sbom
        with:
          image: localbuild/testimage:latest
          artifact-name: sbom.json  # This is the output SBOM file

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: artifacts/image.spdx.json
      
      # Later steps that use the uploaded SBOM
      - name: Run Trivy License Check using SBOM
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: sbom
          input: "artifacts/image.spdx.json"  # Path to the SBOM artifact
          output: "trivy-license-report.json"
          
          
      # Upload the Trivy dependency report
      - name: Upload Trivy dependency report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-dependency-report
          path: trivy-dependency-report.json
